name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run the script
    - run: 
        |
        echo Hello, world! New version pushed! 
        csi chicken-browser.ss
    - continue-on-error: true
